### PR TITLE
adding reth chart

### PR DESCRIPTION
**Pull request by barnabasbusa**
Closes: #168

### CODE REVIEW

**Comment by barnabasbusa** [comment]
Reth won't be able to run in kubernetes nicely till this is merged: https://github.com/paradigmxyz/reth/pull/2495

**Comment by barnabasbusa** [comment]
Current CI fails on this issue https://github.com/paradigmxyz/reth/issues/2529

**Comment by gakonst** [comment]
(Think this PR has some maybe non relevant changes from the ethereumjs work?)

**Comment by barnabasbusa** [comment]
Yeah this branch is branches off of the ethereumjs helm chart which is not yet merged either. This PR should clear up a lot as soon as that's merged.

**Review by skylenet — APPROVED** [review]

**Pull request merged**
