### PR TITLE
Fix/reth ports

### LINKED ISSUE #218: duplicate ports on reth
I am getting the following error with reth chart 0.0.6 and kubernetes 1.27

```
      .spec.template.spec.containers[name="reth"].ports: duplicate entries for key [containerPort=8545,protocol="TCP"]
      .spec.template.spec.containers[name="reth"].ports: duplicate entries for key [containerPort=8551,protocol="TCP"]
```

Passing the following values fixes it:

```
          httpPort: 8544,
          authPort: 8550,
```

However, the default values.yaml should be valid. Thanks in advance

### PR DESCRIPTION
**Pull request by paolofacchinetti**
Closes #218 

- Set the default `wsPort` value to `8546` to reflect the default in Reth shown below:

```
      --ws.port <WS_PORT>
          Ws server port to listen on

          [default: 8546]
```

- Unify `authPort` and `wsAuthPort` by removing the latter, since Reth has only one single `authrpc.port` flag

### CODE REVIEW

**Comment by barnabasbusa** [comment]
Could you please run `make init`, `make docs` and `make lint`. It will fail, as you forgot to bump the chart version. Every modification needs a chart version bump. 
Also could you please merge in  #219 as thats a very minor change, and probably not worth having two releases for such a small example change.

**Comment by paolofacchinetti** [comment]
@barnabasbusa should be ok now, thanks for the feedback

**Review by barnabasbusa — APPROVED** [review]
LGTM

**Comment by paolofacchinetti** [comment]
I see the ci lint failing, does the chart bump need to be the last pushed commit? or is that a known issue and when you squash and merge to master it will take care of itself?

**Comment by barnabasbusa** [comment]
Could you rebase master, and bump to 0.0.8 ? 
Current master is 0.0.7 already. 
https://github.com/ethpandaops/ethereum-helm-charts/blob/master/charts/reth/Chart.yaml#L10

**Comment by barnabasbusa** [comment]
You gotta bump ethereum-nodes too, as you modified that too.

**Comment by paolofacchinetti** [comment]
yeah, i'm sorry for the mess but i'm having issues running `make lint` locally, which is weird because `make docs` works fine. Might be some WSL2 + Docker desktop shenanigans...

I'm getting a `Error: failed linting charts: failed identifying charts to process: must be in a git repository`

**Comment by barnabasbusa** [comment]
Looks like this PR now includes a lot more changes than a few commits before. I'm not really sure the rebase worked out the way we wanted it.

**Comment by paolofacchinetti** [comment]
yeah - I wrongfully rebased master on top of this branch... I'll scrap this and make a new PR from scratch since the changes are trivial. 

Thanks for your patience :')

**Comment by paolofacchinetti** [comment]
closing this in favour of #235

**Pull request closed without merging**
