### PR TITLE
feat: add erpc chart

### LINKED ISSUE #337: Add erpc helm chart

### PR DESCRIPTION
**Pull request by paolofacchinetti**
Adds the [erpc](https://github.com/erpc/erpc) chart and closes #337 

## A few things i'd love to get some feedback on

I based my implementation and the relative config defaults on the [railway-deployment](https://github.com/erpc/railway-deployment) for erpc. I'm not a fan of having the config (which contains remote RPC apikeys) be stored in a configmap, but from how they use gotemplate to load env variables into the config file i assume erpc doesnt support config overrides from environment variables.

The [prepackaged docker image by erpc](https://github.com/erpc/erpc/blob/main/Dockerfile) is hardcoded to run as root. It's fairly easy to change that with a new Dockerfile but we would have to rehost the image on another registry and keep it updated. Not sure on what the policies are for that stuff, but i'm open to discuss

I didnt include postgres or prometheus/grafana since they arent a requirement (nor the default config) and people can just deploy those with the relative charts/operators.

### CODE REVIEW

**Comment by skylenet** [comment]
hey @paolofacchinetti . Thanks for the draft PR!

> The [prepackaged docker image by erpc](https://github.com/erpc/erpc/blob/main/Dockerfile) is hardcoded to run as root.

You could set some default Pod securityContext, which will prevent any containers from that pod to run as root.

Example, in `values.yaml`. We also use this in many other charts:
```sh
securityContext:
  fsGroup: 10001
  runAsGroup: 10001
  runAsNonRoot: true
  runAsUser: 10001
```

> I didnt include postgres or prometheus/grafana since they arent a requirement (nor the default config) and people can just deploy those with the relative charts/operators.

Yeah, that makes sense 👍

**Comment by skylenet** [comment]
> I'm not a fan of having the config (which contains remote RPC apikeys) be stored in a configmap, but from how they use gotemplate to load env variables into the config file i assume erpc doesnt support config overrides from environment variables.

You could have an init container, that mounts the configmap and env vars and then performs an `envsubst` into a file in a shared `emtpyDir` volume (init container <-> erpc container).

**Comment by paolofacchinetti** [comment]
Hey @skylenet, thanks for the feedback!

> You could set some default Pod securityContext, which will prevent any containers from that pod to run as root.
> 
> Example, in `values.yaml`. We also use this in many other charts:
> 
> ```shell
> securityContext:
>   fsGroup: 10001
>   runAsGroup: 10001
>   runAsNonRoot: true
>   runAsUser: 10001
> ```

Done in https://github.com/ethpandaops/ethereum-helm-charts/pull/345/commits/2dbec963e7629c6700f5ad57ee5c4d84521e91a6

I was blocked due to a misbelief that erpc could only look for the config file under the `/root` directory, but looking at their code I noticed it's possible to specify the config file location as the first cli arg of the boot cmd.

> You could have an init container, that mounts the configmap and env vars and then performs an envsubst into a file in a shared emtpyDir volume (init container <-> erpc container).

Done in https://github.com/ethpandaops/ethereum-helm-charts/pull/345/commits/f5a8051bb69d136730ac54b0da97cc514cd24c90

Apparently erpc already performs [env substitution natively](https://github.com/erpc/erpc/blob/7ec6c8065a76d3c0118b6f6e5b851498ea209055/common/config.go#L366C28-L366C37). I'm not sure why the railway deployment goes out of its way to [do it again through a custom Dockerfile](https://github.com/erpc/railway-deployment/blob/main/Dockerfile.erpc#L18), but it's much better this way since we don't need an initContainer.

**Comment by skylenet** [comment]
Awesome! Can you update the content in `charts/erpc/README.md.gotmpl` and regenerate the README.md using `make docs` ? Currently it has a lot of dora references.

**Comment by paolofacchinetti** [comment]
> Awesome! Can you update the content in `charts/erpc/README.md.gotmpl` and regenerate the README.md using `make docs` ? Currently it has a lot of dora references.

Oh you're right, my bad. Now it should be okay 😄

**Pull request merged**
