### PR TITLE
blockscout: update chart for blockscout version 5

### PR DESCRIPTION
**Pull request by jacobhjkim**
## Changes
1. Use [blockscout/blockscout](https://hub.docker.com/r/blockscout/blockscout/) instead of [skylenet/blockscout](https://hub.docker.com/r/skylenet/blockscout/) for the container image repository.
2. Update Blockscout's command args to `"bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"` 
3. Add [smart-contract-verifier-http](https://github.com/ethpandaops/ethereum-helm-charts/tree/master/charts/smart-contract-verifier-http) as a dependency.
4. Add [bitnami/redis](https://github.com/bitnami/containers/tree/main/bitnami/redis) as a dependency.
5. Upgrade Postgres to `11.x.x` since bitnami removed `10.x.x` charts. 

## Notes
(Thanks for this chart repository! Amazing work)

### CODE REVIEW

**Comment by skylenet** [comment]
Thanks @jacobhjkim for updating the blockscout chart :muscle: 
Just glanced through the code and configs and it looks good to me. 
I'll try this out manually in the following days to make sure it works as intended.

**Comment by jacobhjkim** [comment]
Updated PR to apply https://github.com/ethpandaops/ethereum-helm-charts/pull/129.

**Comment by skylenet** [comment]
I am still waiting for 5.0.0 to be released before properly testing this. Seems like it might be getting closer: https://twitter.com/blockscoutcom/status/1605935686959366144?s=20&t=eMucxjdUxr1WniUYMsMmxA

**Comment by jacobhjkim** [comment]
I didn't think it would take this long for 5.0.0 to be released 😅, but 5.0.0 looks great!

**Review by barnabasbusa — APPROVED** [review]

**Pull request merged**
