### PR TITLE
ipfs-cluster: Add additional labels to cluster pod

### PR DESCRIPTION
**Pull request by GuillaumeOuint**
For the issue #271

### CODE REVIEW

**Comment by demostanis** [comment]
could you give some usage examples? in particular "to add prometheus labels to auto scrape the metrics". thank you

**Comment by GuillaumeOuint** [comment]
> could you give some usage examples? in particular "to add prometheus labels to auto scrape the metrics". thank you

It's pretty straightforward, it's adding the capacity to add custom labels on the pod. I should have added custom annotations too as prometheus use annotations for service discovery and not labels. So the original point is incorrect (sorry). BUT, having the possibility to add custom labels/annotations should be supported as a major part of helm charts online support that (it's more or less in the helm "standard"). So I think this doesn't need usage examples, as labels/annotations can be used for any usage (prometheus, metallb, other operators...). So this feature SHOULD exist on this chart to let users customize their deployment to their needs. Chart author shouldn't limit what labels/annotations we want to put on an object, authors should always let the user choose additional labels/annotations.

Also, as the issue is open for more than a year (and the merge request closed), I took the liberty to fork this chart to add those features. [ipfs-cluster](https://github.com/GuillaumeOuint/helm-charts/tree/main/charts/ipfs-cluster)

**Comment by demostanis** [comment]
thanks for your answer. after reading ipfs-cluster's documentation a bit, i figured out that metrics/tracing requires modification to ipfs-cluster's service.json. i did not find anything in this repo's chart relating to this. how did you manage to do it? does your chart provide a way to customize service.json? or maybe through environment variables i missed? i found someone spawning a job that execs into each ipfs-cluster replica to modify service.json, but it seems hacky.

**Comment by GuillaumeOuint** [comment]
> thanks for your answer. after reading ipfs-cluster's documentation a bit, i figured out that metrics/tracing requires modification to ipfs-cluster's service.json. i did not find anything in this repo's chart relating to this. how did you manage to do it? does your chart provide a way to customize service.json? or maybe through environment variables i missed? i found someone spawning a job that execs into each ipfs-cluster replica to modify service.json, but it seems hacky.

With my chart (don't remember if it's the case here) I have a init script that run on every node before running the daemon that use the "ipfs config" command to change settings in the ipfs kubo config. But for cluster instances I don't have anything and manual edit of the file is needed (or via initcontainer)

**Comment by demostanis** [comment]
in my use case i need to modify the cluster config, not the ipfs config. as i see there's no way to set initContainers using values.yml, only for ipfs pods?

**Comment by demostanis** [comment]
i figured out i could modify service.json by defining environment variables:
```
        cluster:
          extraEnv:
            - name: CLUSTER_TRACING_ENABLETRACING
              value: "true"
            - name: CLUSTER_TRACING_JAEGERAGENTENDPOINT
              value: "/dns/jaeger-agent.grafana.svc.cluster.local/udp/6831"
```

**Pull request closed without merging**
